### ISSUE TITLE
Pixel 4 XL, Android 13 | Blank viewfinder

### ISSUE THREAD

**Issue by irtazafaheem** [Arnova8G2/Gcam_8.7.250.44#10]
Blank viewfinder, and cannot take a picture with the back camera by pressing the shutter button either.
---- Device Info ----
 - Brand : google
 - Model : Pixel 4 XL
 - Manufacturer : Google
 - Device : coral
 - Os version : Android 13 - 4.14.289-gcbeaad5833e7
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by Arnova8G2** [comment]
@irtazafaheem , Can you make a logcat please, thanks

**Comment by mdshafiqulislamshamim** [comment]
Go to developer settings (can use activity launcher app for going directly to settings), then search physical_raw. See the option is enabled or disabled. If disabled, just enable it. Then it will work. Otherwise device interface and hdr interface have to be coral.

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
