### ISSUE TITLE
Black VF 

### ISSUE THREAD

**Issue by JeanLuc40800** [Arnova8G2/Gcam_8.7.250.44#12]
Doesn't work on Pixel4xl, black viewfinder and inoperative shutter button.
---- Device Info ----
 - Brand : google
 - Model : Pixel 4 XL
 - Manufacturer : Google
 - Device : coral
 - Os version : Android 13 - 4.14.276-g6ef255005cea-ab9062920
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by Arnova8G2** [comment]
@JeanLuc40800 , Can you make a logcat please, thanks

**Comment by mdshafiqulislamshamim** [comment]
> Doesn't work on Pixel4xl, black viewfinder and inoperative shutter button. ---- Device Info ----
> 
> * Brand : google
> * Model : Pixel 4 XL
> * Manufacturer : Google
> * Device : coral
> * Os version : Android 13 - 4.14.276-g6ef255005cea-ab9062920
>   ---- Gcam Mod Info ----
> * PackageName : arn.android.gcam
> * VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

Enable physical_raw from developer settings
