### ISSUE TITLE
Okay sir. Good luck 

### ISSUE THREAD

**Issue by mdshafiqulislamshamim** [Arnova8G2/Gcam_8.7.250.44#13]

**Comment by Arnova8G2** [comment]
you have 8.8 decrypt, a little lazy to do so, but without the deletion of debugging lines ?

**Comment by mdshafiqulislamshamim** [comment]
> @mdshafiqulislamshamim you have 8.8 decrypt, a little lazy to do so, but without the deletion of debugging lines ?

Sir my friends are working on it. I am giving u a telegram group link https://t.me/+FLA0IfRXARExYzFl

**Comment by Arnova8G2** [comment]
> > @mdshafiqulislamshamim you have 8.8 decrypt, a little lazy to do so, but without the deletion of debugging lines ?
> 
> Sir my friends are working on it. I am giving u a telegram group link https://t.me/+FLA0IfRXARExYzFl

It's nice, but I don't think it would be good, because some files like the ones I would call code interpretations are very important, it will force to correct codes that shouldn't be or delete getclass to ignore the errors.

**Comment by mdshafiqulislamshamim** [comment]
> > > @mdshafiqulislamshamim you have 8.8 decrypt, a little lazy to do so, but without the deletion of debugging lines ?
> > 
> > 
> > Sir my friends are working on it. I am giving u a telegram group link https://t.me/+FLA0IfRXARExYzFl
> 
> It's nice, but I don't think it would be good, because some files like the ones I would call code interpretations are very important, it will force to correct codes that shouldn't be or delete getclass to ignore the errors.

I will ve free after 2.5 month sir. There is an.exam. Then i will be free. I will work on decrypting the future apk myself sir.

**Comment by mdshafiqulislamshamim** [comment]
> > I will be free after 2.5 month sir. There is an.exam. Then i will be free. I will work on decrypting the future apk myself sir. .source, .line every debug will be available there sir as google.
> 
> I'll wait, if nothing new in 8.8 I won't do it this version, if there are nice new things I'll decrypting .
> 
> Thanks,

Thanks you, sir. Here is the comparison between gcam 8.7.250 vs gcam 8.8. :- https://youtu.be/ozdq62i-ccU . You can have a look, sir

**Comment by Arnova8G2** [comment]
What is this xml bug for A11?
