### ISSUE TITLE
front cam crash

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#15]
front cam of the device freezes then crash, but works when zoomed in
---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by HKR001** [comment]
[arn_gcam.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11071759/arn_gcam.txt)
log file

**Comment by Arnova8G2** [comment]
enabled log and send all file txt ( compress in zip ) adding #16 in log

![Screenshot_2023-03-26-17-32-56-052_com google android GoogleCamera](https://user-images.githubusercontent.com/40323300/227786622-db5fc318-f9b8-4b5e-9053-0c1c4ea23b97.jpg)
![Screenshot_2023-03-26-17-33-19-215_com mixplorer beta](https://user-images.githubusercontent.com/40323300/227786627-4d471057-c664-4005-8893-f6996d4d82f7.jpg)

**Comment by HKR001** [comment]
#16 
[arn_8.7_spes.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072222/arn_8.7_spes.zip)

**Comment by Arnova8G2** [comment]
> #16 [arn_8.7_spes.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072222/arn_8.7_spes.zip)
Test this
![Screenshot_2023-03-26-21-42-42-626_arn android gcam](https://user-images.githubusercontent.com/40323300/227815551-e5592448-6496-4f45-963a-3223fdd6bf6f.jpg)
![Screenshot_2023-03-27-02-33-04-289_com google android GoogleCamera](https://user-images.githubusercontent.com/40323300/227815553-d664d98a-a00a-4fb0-ae96-ce4240c810be.jpg)
![Screenshot_2023-03-27-02-35-36-712_com google android GoogleCamera](https://user-images.githubusercontent.com/40323300/227815554-eafaed50-1aa3-4edf-b278-45c1f49ac52e.jpg)
![Screenshot_2023-03-27-02-36-09-977_com google android GoogleCamera](https://user-images.githubusercontent.com/40323300/227815555-3e83de5d-aea0-420c-bdd2-c8cb466f9ef3.jpg)

**Comment by HKR001** [comment]
Front cam still crashes for redmi note 11

[front_crash_Logs_2023-04-16_11-21-37.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11241294/front_crash_Logs_2023-04-16_11-21-37.zip)

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
