### ISSUE TITLE
video not working

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#16]
[arn_gcam.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11071777/arn_gcam.txt)
video mode black screen and buttons grey out
---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by mdshafiqulislamshamim** [comment]
> [arn_gcam.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11071777/arn_gcam.txt) video mode black screen and buttons grey out ---- Device Info ----
> 
> * Brand : Redmi
> * Model : 2201117TG
> * Manufacturer : Xiaomi
> * Device : spes
> * Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
>   ---- Gcam Mod Info ----
> * PackageName : arn.android.gcam
> * VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

Disable camcorder.codec_sm and camcorder.codec_video from developer settings

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
