### ISSUE TITLE
aux cam crash

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#17]
+ wrong aux cam id detection
+ aux cam crash during hdr+ processing

Log- 
[aux_crash_spes_8.7.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072453/aux_crash_spes_8.7.zip)
[aux_wrong_id_hdr_crash_8.7.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072454/aux_wrong_id_hdr_crash_8.7.zip)

---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by mdshafiqulislamshamim** [comment]
> 



> * wrong aux cam id detection
> * aux cam crash during hdr+ processing
> 
> Log- [aux_crash_spes_8.7.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072453/aux_crash_spes_8.7.zip) [aux_wrong_id_hdr_crash_8.7.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072454/aux_wrong_id_hdr_crash_8.7.zip)
> 
> ---- Device Info ----
> 
> * Brand : Redmi
> * Model : 2201117TG
> * Manufacturer : Xiaomi
> * Device : spes
> * Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
>   ---- Gcam Mod Info ----
> * PackageName : arn.android.gcam
> * VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

Aux cam crashing while hdr processing because of rectiface_support_level. Just select the value 0.

**Comment by HKR001** [comment]
enabling aux lenes crashes the app beta6

[aux_crash_Logs_2023-04-16_11-39-23.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11241321/aux_crash_Logs_2023-04-16_11-39-23.zip)

**Comment by HKR001** [comment]
UW crashes instantly similar to #41

[Logs_2023-04-27_10-03-22.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11339447/Logs_2023-04-27_10-03-22.zip)

**Comment by Arnova8G2** [comment]
fixed : https://www.celsoazevedo.com/files/android/google-camera/dev-arnova8G2-beta/f/dl17/
