### ISSUE TITLE
low res photo

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#18]
photo taken with the camera stay at 8mp despite being higher resolution sensor

Log-
[low_res_photo_8.7.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072465/low_res_photo_8.7.txt)

---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by mdshafiqulislamshamim** [comment]
> photo taken with the camera stay at 8mp despite being higher resolution sensor
> 
> Log- [low_res_photo_8.7.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072465/low_res_photo_8.7.txt)
> 
> ---- Device Info ----
> 
> * Brand : Redmi
> * Model : 2201117TG
> * Manufacturer : Xiaomi
> * Device : spes
> * Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
>   ---- Gcam Mod Info ----
> * PackageName : arn.android.gcam
> * VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

Select raw_sensor

**Comment by HKR001** [comment]
> > photo taken with the camera stay at 8mp despite being higher resolution sensor
> > Log- [low_res_photo_8.7.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11072465/low_res_photo_8.7.txt)
> > ---- Device Info ----
> > 
> > * Brand : Redmi
> > * Model : 2201117TG
> > * Manufacturer : Xiaomi
> > * Device : spes
> > * Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
> >   ---- Gcam Mod Info ----
> > * PackageName : arn.android.gcam
> > * VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309
> 
> Select raw_sensor

Unfortunately, I didn't find such settings in the app.

**Comment by HKR001** [comment]
Here is the media dump suggested in #28 

[camera2dumpsys-redmi_note_11.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11241314/camera2dumpsys-redmi_note_11.zip)

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1

**Comment by HKR001** [comment]
`camera.pck_postprocess_rawsensor`

not working in v8.2-b1

[low_res_photo.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11471713/low_res_photo.zip)
