### ISSUE TITLE
Asset error

### ISSUE THREAD

**Issue by rakinthegreat** [Arnova8G2/Gcam_8.7.250.44#2]
![Screenshot (610)](https://user-images.githubusercontent.com/66740314/213741144-002a8118-ea70-4af3-9c10-ea8728da56f0.png)

This is the cause: 
![image](https://user-images.githubusercontent.com/66740314/213741378-eaf31b1c-556b-44f2-9cc3-9484fcc29513.png)

**Comment by Arnova8G2** [comment]
it seems that the bug is at sign

**Comment by rakinthegreat** [comment]
Is there anyway to fix this?

**Comment by Arnova8G2** [comment]
> 

makes a sign key without password, me it's without password and I've been using it for 3 years

**Comment by Arnova8G2** [comment]
https://github.com/Arnova8G2/Gcam_8.7.250.44_smali/releases/tag/V8.0

**Comment by Arnova8G2** [comment]
https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.0

**Comment by rakinthegreat** [comment]
> > 
> 
> makes a sign key without password, me it's without password and I've been using it for 3 years

I have tried without a password and still not working

**Comment by Arnova8G2** [comment]
> I have tried without a password and still not working

New GcamApkTool
https://drive.google.com/file/d/1eusfocjWuSXfPmshEbFgkYdjEMk65p3F/view?usp=share_link

- Add camera2dumpsys Mod
- Add Logcat Mod
- Add All Framework
- Add AndroidSDK-33.0.1
- Add Platform-tools-33.0.3
- Add Change paquetage name in apk
- Add Auto generat APK certificate fingerprints and hashes
- Add Auto number version in apk

**Comment by Arnova8G2** [comment]
I just downloaded and you are right same error
![image](https://user-images.githubusercontent.com/40323300/213936057-988138ef-bdb2-44ce-ba41-d1633e5c4d54.png)

I will compare with one I have

**Comment by Arnova8G2** [comment]
strange it is identical
![image](https://user-images.githubusercontent.com/40323300/213936251-9cdb0204-a877-421b-86a6-afa03f698670.png)

**Comment by Arnova8G2** [comment]
with my sign key is good, but sign testkey that I added in gcamTool has the same bug

![image](https://user-images.githubusercontent.com/40323300/213936691-fb537377-3359-4523-929b-fa0bb329f521.png)

**Comment by Arnova8G2** [comment]
with your signed key
![image](https://user-images.githubusercontent.com/40323300/213937079-5ae74ea5-de17-41c0-a357-e03e20e21286.png)
![image](https://user-images.githubusercontent.com/40323300/213937132-2930b069-a74f-44c5-9a19-810a45413a2c.png)
