### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by flashkingv** [Arnova8G2/Gcam_8.7.250.44#21]
Crashes when i tap the shutter.
---- Device Info ----
 - Brand : samsung
 - Model : SM-G975F
 - Manufacturer : samsung
 - Device : beyond2
 - Os version : Android 12 - 4.14.113-25257816
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by Arnova8G2** [comment]
@flashkingv, enabled log and send all file txt ( compress in zip ) 

![Screenshot_2023-03-26-17-32-56-052_com google android GoogleCamera](https://user-images.githubusercontent.com/40323300/227786622-db5fc318-f9b8-4b5e-9053-0c1c4ea23b97.jpg)
![Screenshot_2023-03-26-17-33-19-215_com mixplorer beta](https://user-images.githubusercontent.com/40323300/227786627-4d471057-c664-4005-8893-f6996d4d82f7.jpg)

**Comment by omaralwardian** [comment]
> Crashes when i tap the shutter. ---- Device Info ----
> 
> * Brand : samsung
> * Model : SM-G975F
> * Manufacturer : samsung
> * Device : beyond2
> * Os version : Android 12 - 4.14.113-25257816
>   ---- Gcam Mod Info ----
> * PackageName : **arn.android.gcam**
> * VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

@flashkingv 
I'm not the developer but I can help. 
Download the updated beta, but make sure you get the Scan3D package. 

This is the file name you want to download:
**Gcam-8.7.250.build-8.0Beta5_scan3d.apk**

**Comment by flashkingv** [comment]
I did but it still crashes 😞

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
