### ISSUE TITLE
Crashing on the OnePlus 8 Pro

### ISSUE THREAD

**Issue by celsoazevedo** [Arnova8G2/Gcam_8.7.250.44#22]
Crashes as soon as we open the app, but it's possible to access the settings via the shortcut (that's how I saved the log).

---- Device Info ----
 - Brand : OnePlus
 - Model : IN2023
 - Manufacturer : OnePlus
 - Device : OnePlus8Pro
 - Os version : Android 13 - 4.19.275-perf-g983184d81a23
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta5.230410.1723

**Comment by celsoazevedo** [comment]
Log:

[logs_v8.7_0.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11202350/logs_v8.7_0.txt)

**Comment by Arnova8G2** [comment]
@celsoazevedo, thanks for log, this is a bug with custom AWBs, I will fix this

**Comment by Arnova8G2** [comment]
@celsoazevedo , New version : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/8.0-beta6
