### ISSUE TITLE
Crash on S23U

### ISSUE THREAD

**Issue by SkyKing0007** [Arnova8G2/Gcam_8.7.250.44#23]
[logs_v8.7_0.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11202744/logs_v8.7_0.txt)

**Comment by Arnova8G2** [comment]
@SkyKing0007 
This is a bug with custom AWBs, I will fix this

**Comment by SkyKing0007** [comment]
> Try this to resolve.

This do not work.

**Comment by Arnova8G2** [comment]
@SkyKing0007 , New version : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/8.0-beta6

**Comment by SkyKing0007** [comment]
> @SkyKing0007 , New version : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/8.0-beta6

[Logs_2023-04-15_08-04-49.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11239366/Logs_2023-04-15_08-04-49.zip)

I set ID as back: 56, ultrawide:2, tele 3x: 52, front:1.  Still crashed.  I did not even set opmode, but if opmode is needed, can you set default for samsung?  Too many to try.

**Comment by Arnova8G2** [comment]
> I set ID as back: 56, ultrawide:2, tele 3x: 52, front:1. Still crashed. I did not even set opmode, but if opmode is needed, can you set default for samsung? Too many to try.

You used two identical id, made a dump camera 
![image](https://user-images.githubusercontent.com/40323300/232249000-26d05bb3-9dea-4c1b-96a5-2ae6783ea9c0.png)

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
