### ISSUE TITLE
doesnt open camera

### ISSUE THREAD

**Issue by umejnarukolaps** [Arnova8G2/Gcam_8.7.250.44#24]
realme gt neo 2
---- Device Info ----
 - Brand : realme
 - Model : RMX3370
 - Manufacturer : realme
 - Device : RE879AL1
 - Os version : Android 13 - 4.19.157-perf 
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta5.230410.1723

**Comment by Arnova8G2** [comment]
@umejnarukolaps , do a logcat to check error

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
