### ISSUE TITLE
Crashes after clicking the shutter.

### ISSUE THREAD

**Issue by flashkingv** [Arnova8G2/Gcam_8.7.250.44#30]
The app crashes everytime i click the shutter but it is fine on video record.
---- Device Info ----
 - Brand : samsung
 - Model : SM-G975F
 - Manufacturer : samsung
 - Device : beyond2
 - Os version : Android 12 - 4.14.113-25257816
---- Gcam Mod Info ----
 - PackageName : com.samsung.android.scan3d
 - VersionName : 8.7.250.build-8.0Beta5.230410.1726

**Comment by Arnova8G2** [comment]
> The app crashes everytime i click the shutter but it is fine on video record.

make a logcat of crash and share zip file in gcam/log folder
![Screenshot_2023-04-17-23-08-15-858_app lawnchair debug-edit](https://user-images.githubusercontent.com/40323300/232611415-1c537adf-fc56-4891-940f-4b83b83308bb.jpg)

**Comment by flashkingv** [comment]
What app should I use to make a logcat?

**Comment by Arnova8G2** [comment]
> What app should I use to make a logcat?

https://www.celsoazevedo.com/files/android/google-camera/dev-arnova8G2-beta/f/dl16/

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
