### ISSUE TITLE
Front Video Black Viewfinder 

### ISSUE THREAD

**Issue by myselflatu** [Arnova8G2/Gcam_8.7.250.44#31]
#@
[Logs_2023-04-21_21-31-08.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11297455/Logs_2023-04-21_21-31-08.zip)
Switching To Front Lens On Video Makes Viewfinder Black And Breaks Camera After That Nothing Works Till I Reboot
  ---- Device Info ----
 - Brand : POCO
 - Model : M2102J20SI
 - Manufacturer : Xiaomi
 - Device : bhima
 - Os version : Android 12 - 4.14.180-perf-g7b73a8812310
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0.230421.1010

**Comment by Arnova8G2** [comment]
@myselflatu , It is a bug of zoom badly detected, from 1.1 it works, I will correct next version  
Thanks for your feedback

**Comment by myselflatu** [comment]
Thank you for all your work 🙏 . ALSO please add a option to save config ir GCA like previous versions would be very helpful.
