### ISSUE TITLE
Realme GT Master Wide Camera Crash

### ISSUE THREAD

**Issue by celsoazevedo** [Arnova8G2/Gcam_8.7.250.44#32]
Report of a crash ([on XDA](https://forum.xda-developers.com/t/app-arnova8g2s-google-camera-port.3862448/post-88443545)) of the wide camera crashing when HDR Enhanced is used.

Phone: Realme GT Master

==============================================
Created : 2023-04-21_15-09-01
Brand : realme
Model : RMX3363
Manufacturer : realme
Device : RE54ABL1
Os version : Android 13 - 5.4.226-qgki-g590cff13face-dirty
----Gcam Mod Info----
PackageName : com.google.android.GoogleCamera
VersionName : 8.7.250.build-8.0.230421.1011
Device CodeName : 0

**Comment by celsoazevedo** [comment]
[logs_v8.7_0.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11298297/logs_v8.7_0.txt)

**Comment by Arnova8G2** [comment]
> [logs_v8.7_0.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11298297/logs_v8.7_0.txt)
In log seems to be a bug with raw sensor format 
or
Force sabre in dev ( camera.sabre_force ) now works on a large number of sensors or disables "camera.sabre_spatial_rgb_enabled" .
