### ISSUE TITLE
Black pictures in low light

### ISSUE THREAD

**Issue by celsoazevedo** [Arnova8G2/Gcam_8.7.250.44#33]
Some reports (8.7 v8.0 stable) of pictures coming out black when in low light.

I can reproduce it on my OP8 Pro. osm0sis [also experiences](https://forum.xda-developers.com/t/app-arnova8g2s-google-camera-port.3862448/post-88443647) the same problem on his OnePlus 9 Pro.

To reproduce:
- Open GCam.
- Take a picture in low light.
- The thumbnail will initially show some light.
- The processed file is completely black.

**Comment by Arnova8G2** [comment]
> Some reports (8.7 v8.0 stable) of pictures coming out black when in low light.

I will make a fix version for this bug

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
