### ISSUE TITLE
Switching From 2x Video To 1x Stops Video Recording

### ISSUE THREAD

**Issue by myselflatu** [Arnova8G2/Gcam_8.7.250.44#34]
This Seems To Happen Only If I Use Aux Button To Switch Lens , If I Pinch Zoom In Or Out Everything Seems Fine
  ---- Device Info ----
 - Brand : POCO
 - Model : M2102J20SI
 - Manufacturer : Xiaomi
 - Device : bhima
 - Os version : Android 12 - 4.14.180-perf-g7b73a8812310
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0.230421.1010

**Comment by myselflatu** [comment]
[Uploading Logs_2023-04-22_13-40-09.zip…]()

**Comment by myselflatu** [comment]
[Logs_2023-04-22_13-40-09.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11300635/Logs_2023-04-22_13-40-09.zip)

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1

**Comment by myselflatu** [comment]
just tried it and can confirm the issue has been fixed!! Thanks 🙏
