### ISSUE TITLE
Turning Off Social Share Feature Of Crashes The App

### ISSUE THREAD

**Issue by myselflatu** [Arnova8G2/Gcam_8.7.250.44#35]
This can be avoided if instead of turning the main toggle off directly you disable the options on the app individually
  ---- Device Info ----
 - Brand : POCO
 - Model : M2102J20SI
 - Manufacturer : Xiaomi
 - Device : bhima
 - Os version : Android 12 - 4.14.180-perf-g7b73a8812310
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.1.230424.2015

**Comment by myselflatu** [comment]
[Logs_2023-04-25_01-06-08.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11314040/Logs_2023-04-25_01-06-08.zip)

**Comment by Arnova8G2** [comment]
> [Logs_2023-04-25_01-06-08.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11314040/Logs_2023-04-25_01-06-08.zip)

I will update by replacing with a new 8.1

**Comment by myselflatu** [comment]
Also the previous black viewfinder front lens video bug we talked about seems to persist in this new version too and as you said earlier works if i twice to the zoomed (1.4x)

**Comment by Arnova8G2** [comment]
> Also the previous black viewfinder front lens video bug we talked about seems to persist in this new version too and as you said earlier works if i twice to the zoomed (1.4x)

A yes I had forgotten if you can open an issue of this bug, thank you

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
