### ISSUE TITLE
Black Viewfinder on front lens video (Unzoomed) 

### ISSUE THREAD

**Issue by myselflatu** [Arnova8G2/Gcam_8.7.250.44#36]
[Logs_2023-04-25_01-44-38.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11314340/Logs_2023-04-25_01-44-38.zip)

**Comment by Arnova8G2** [comment]
> [Logs_2023-04-25_01-44-38.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11314340/Logs_2023-04-25_01-44-38.zip)

@myselflatu , in dev "camera.p20_lens_setup" might fix your bug

**Comment by myselflatu** [comment]
That seems to work thanks 🙏
