### ISSUE TITLE
Macro Lens Not Working

### ISSUE THREAD

**Issue by myselflatu** [Arnova8G2/Gcam_8.7.250.44#38]
Macro Lens Isn't Detected By The Aux. While looking at the aux settings i found that there no id section for rear macro/tele for every other lens it's present as you can see in the screenshot.
![Screenshot_2023-04-25-09-37-16-512_com google android GoogleCamera](https://user-images.githubusercontent.com/40817763/234172664-7f654099-b7c5-4833-89b4-649453c4fa84.jpg)

If there's some issue, i think it would be nice to have a option to disable or hide it in aux so that it won't feel a bit weird having a aux button that ain't working in the menu.

**Comment by Arnova8G2** [comment]
@myselflatu , I use names created by google, macro is not in their code, I'll see how I can add it and detect it.

Google names:
WIDE = main cam
TELE = zoom 2x
ULTRAWIDE = ultra wide
ULTRATELE = telephoto
DEPTH = depth and can detect macro cam

**Comment by Arnova8G2** [comment]
Add 
![image](https://user-images.githubusercontent.com/40323300/235313292-1658f434-65c2-4c28-93a1-94f5445b86b4.png)

**Comment by Arnova8G2** [comment]
Fixed : https://www.celsoazevedo.com/files/android/google-camera/dev-arnova8G2-beta/f/dl17/
