### ISSUE TITLE
AWB gains

### ISSUE THREAD

**Issue by JohnSasoriza** [Arnova8G2/Gcam_8.7.250.44#4]
Photos come out green on Redmi Note 11 even with active AWB
---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 12 - 4.19.157-perf-g1514072743bd
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2309

**Comment by Arnova8G2** [comment]
> Photos come out green on Redmi Note 11 even with active AWB ---- Device Info ----

Test with setting and share a capture

![Screenshot_2023-03-26-05-38-04-929_com google android GoogleCamera](https://user-images.githubusercontent.com/40323300/227754015-2c96b16e-2d98-42db-82ff-9ad74a4aabf2.jpg)

**Comment by JohnSasoriza** [comment]
Problem solved, thank you very much 🙏

**Comment by HKR001** [comment]
awb gain not working in beta6

![Screenshot_20230411-215632_Trebuchet](https://user-images.githubusercontent.com/36487189/232249963-139c9a93-0fc8-464f-8123-6b1a66ae6cd3.png)


[awb_gain_Logs_2023-04-16_01-30-50.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11240460/awb_gain_Logs_2023-04-16_01-30-50.zip)

**Comment by Arnova8G2** [comment]
> [awb_gain_Logs_2023-04-16_01-30-50.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11240460/awb_gain_Logs_2023-04-16_01-30-50.zip)

In this release
Settings -> Advanced -> AWB Config each camera will use are AWB, can even use txt files

**Comment by HKR001** [comment]
Have managed to resolve the issue with **awb toggle on (in viewfinder) + p6pro** combinations. However, awb.txt not working, other pixel wb not working

> > [awb_gain_Logs_2023-04-16_01-30-50.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11240460/awb_gain_Logs_2023-04-16_01-30-50.zip)
> 
> In this release Settings -> Advanced -> AWB Config each camera will use are AWB, can even use txt files
> 
> ex file awb : [Vayu_Sunny_Imx582_Main_awb.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11240495/Vayu_Sunny_Imx582_Main_awb.txt)
