### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#41]
the app crash instantly after taking the shot
  ---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.1.230424.2158

[Logs_2023-04-27_09-58-16.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11339442/Logs_2023-04-27_09-58-16.zip)

**Comment by Arnova8G2** [comment]
https://github.com/Arnova8G2/Gcam_8.7.250.44/issues/20
