### ISSUE TITLE
front cam freezes and crash

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#42]
the front cam isn't working for any mode. interestingly it works (no freezes/ crash) when applying 1.4x zoom
  ---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.1.230424.2158

[Logs_2023-04-27_10-15-37.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11339490/Logs_2023-04-27_10-15-37.zip)

**Comment by Arnova8G2** [comment]
use in dev "camera.p20_lens_setup"

**Comment by HKR001** [comment]
> use in dev "camera.p20_lens_setup"

Still crash with latest release
[Logs_2023-05-14_16-29-19.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11471685/Logs_2023-05-14_16-29-19.zip)
