### ISSUE TITLE
GCam Gboard issue

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#43]
GCam dev settings' **search** functionality isn't working after recent Gboard [update](https://www.apkmirror.com/apk/google-inc/gboard/gboard-12-9-10-521739039-release/). I have tested on other gcam mod and it behaves similarly. In fact I have tried with vanilla build of lineage os with [GCam-service-provider](https://github.com/lukaspieper/Gcam-Services-Provider) in combination with AOSP keyboard and the **search** functionality doesn't work similar to recent Gboard.

logs (tested on v8.1 and bsg 8.7 v15)
[gcam_gboard_issue.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11339586/gcam_gboard_issue.zip)

**Comment by Arnova8G2** [comment]
Fixed
![image](https://user-images.githubusercontent.com/40323300/235276943-53ae028d-4802-4340-91bd-0147f3c526cf.png)

**Comment by Arnova8G2** [comment]
Fixed : https://www.celsoazevedo.com/files/android/google-camera/dev-arnova8G2-beta/f/dl17/
