### ISSUE TITLE
OnePlus 7T, Oxygen 12

### ISSUE THREAD

**Issue by drishd** [Arnova8G2/Gcam_8.7.250.44#44]
[Logs_2023-04-29_21-02-16.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11359546/Logs_2023-04-29_21-02-16.zip)
Slow motion not working
  ---- Device Info ----
 - Brand : OnePlus
 - Model : HD1903
 - Manufacturer : OnePlus
 - Device : OnePlus7T
 - Os version : Android 12 - 4.14.180-perf 
---- Gcam Mod Info ----
 - PackageName : com.google.android.GoogleCamera
 - VersionName : 8.7.250.build-8.1.230424.2152

**Comment by Arnova8G2** [comment]
@drishd , Here's what to enable
![Screenshot_20230429-181441_Appareil photo](https://user-images.githubusercontent.com/40323300/235312747-c88253ee-172e-4feb-ba6f-4fb8db794b1d.png)
![Screenshot_20230429-181509_Appareil photo](https://user-images.githubusercontent.com/40323300/235312749-bfba5cc4-e189-48ee-bb1a-bba7989d60ac.png)

**Comment by drishd** [comment]
Thank you 🙏🏻Sir. 1/8X is working. But... 1/4X crashing. It's not a
problem. I've one more problem, photos from front cam are some what
darker..., particularly faces. Is there a way to increase exposure...in Dev
settings?
Thank you 🙏🏻 once again.
