### ISSUE TITLE
UW & Macro Lens Giving 2MP Outputs

### ISSUE THREAD

**Issue by myselflatu** [Arnova8G2/Gcam_8.7.250.44#46]
[Logs_2023-05-14_14-19-05.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11471498/Logs_2023-05-14_14-19-05.zip)

**Comment by Arnova8G2** [comment]
> [Logs_2023-05-14_14-19-05.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11471498/Logs_2023-05-14_14-19-05.zip)

Your device uses small resolution for raw format
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/abde0b5c-bafe-4800-b712-d3e6c792a894)

**Comment by myselflatu** [comment]
@Arnova8G2 But it was working fine in previous build i think

**Comment by Arnova8G2** [comment]
@myselflatu 
test this : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.4-Beta1

**Comment by myselflatu** [comment]
> @myselflatu test this : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.4-Beta1

Yeah seems fine with this
