### ISSUE TITLE
Hdr processing.

### ISSUE THREAD

**Issue by mdshafiqulislamshamim** [Arnova8G2/Gcam_8.7.250.44#5]
Rectiface_support_level 0 only works. But 1 and 2 doesn't work. Sir I will recommend you to take the codes from gcam 8.8 latest. Google didn't encrypt hdr processing codes there and code logic is also similar as 8.3.
---- Device Info ----
 - Brand : Redmi
 - Model : 220333QAG
 - Manufacturer : Xiaomi
 - Device : fog
 - Os version : Android 12 - 4.19.157-perf-g85e27949fb09
---- Gcam Mod Info ----
 - PackageName : com.google.android.GoogleCamera
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2313

**Comment by Arnova8G2** [comment]
> Rectiface_support_level 0 only works. But 1 and 2 doesn't work. Sir I will recommend you to take the codes from gcam 8.8 latest. Google didn't encrypt hdr processing codes there and code logic is also similar as 8.3.

Thank you, I'll see if it works, but the rectiface full=1 and front = 2 processing codes don't cause the bug, I haven't finished analyzing them to understand them.

code i extracted from dogfood 8.xx
![image](https://user-images.githubusercontent.com/40323300/227773114-aba1d3c0-9d18-4e85-8388-6670f9ec3ac1.png)

**Comment by mdshafiqulislamshamim** [comment]
Sir, rectiface_support_level also related to lens distortion (It works if rectiface_support_level is 1 or 2) for wide cam.

**Comment by Arnova8G2** [comment]
OK, we add rgbToYuv in 8.8, which did not exist on previous ones
![image](https://user-images.githubusercontent.com/40323300/227774848-4bbcf876-9bae-477e-9d2c-9744d38701ee.png)

**Comment by mdshafiqulislamshamim** [comment]
Okay sir

**Comment by mdshafiqulislamshamim** [comment]
Then sir, it will be pretty hard to fix all issues related to hdr processing. Hdr+ enhanced still not working on many devices because of hdr processing code issue but hdr+ works for many devices. We still using hdr processing codes from 8.3 is not suitable enough for 8.7. Hdr processing codes never gives crash log so  i added log to understand which and which codes are running. Then i found when the method return with RGB, selfie mirror doesn't work. If i skip that, it was working. But gcam 8.6 had no issues with that codes.

**Comment by Arnova8G2** [comment]
shouldFlip =  mirror
b2 = processprimary
postprocessingImage7.b = yuv
postprocessingImage7.a = rgb

![image](https://user-images.githubusercontent.com/40323300/227784514-5546638f-f37a-4778-b9f0-8aa73e157364.png)

but i will see how 8.8 works

**Comment by mdshafiqulislamshamim** [comment]
Great sir.

**Comment by Arnova8G2** [comment]
it's true that a lot of code was missing for HdrPlusPostProcessing
![image](https://user-images.githubusercontent.com/40323300/227806332-d07d5eae-fcbc-41d3-ac80-7cb34c2fd811.png)

**Comment by mdshafiqulislamshamim** [comment]
Yes sir. Exactly.

**Comment by mdshafiqulislamshamim** [comment]
![Screenshot_2023-03-27-12-39-07-213_ch.want.imagecompare.jpg](https://user-images.githubusercontent.com/90249842/227860356-ea22a8ab-08e2-45d4-8b48-f3a710cb241c.jpg)

Top: gcam 8.8 with default settings
Bottom: gcam 8.7 with default settings

Main difference that i noticed is sky color
