### ISSUE TITLE
Low res output 

### ISSUE THREAD

**Issue by AT0M-03** [Arnova8G2/Gcam_8.7.250.44#50]
before anything Thanks for fixing bugs and listening to the community
But adding raw sensor in the new beta build doesn't fix the issue in my case because my device doesn't support raw16 only raw 10 enabling this option will result crashing the cam

_Originally posted by @AT0M-03 in https://github.com/Arnova8G2/Gcam_8.7.250.44/issues/28#issuecomment-1546658325_

**Comment by AT0M-03** [comment]
![logs_v8.7_0.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11502993/logs_v8.7_0.txt)

**Comment by AT0M-03** [comment]
![Screenshot_2023-05-18-02-10-53-092_cn.wps.moffice_eng-edit~2.jpg](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/130800451/eb7ad9a4-317a-4e08-8b86-7ccbe518295c)

Ialso noticed that gcam merges the original res of my sensor but somehow it gets downsampled as mentioned in the photo

**Comment by Arnova8G2** [comment]
> Ialso noticed that gcam merges the original res of my sensor but somehow it gets downsampled as mentioned in the photo

This is resolution of main camera ? 
if you want to check all gcam info on a capture.
Activate gcam.debug in dev, take a capture you will have this in gcam/log folder

![Screenshot_2023-05-18-11-11-36-792_com mixplorer](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/0cf8f3d7-422a-49c6-ad04-0551c9214e5b)

You will also have all frames in PNG

![Screenshot_2023-05-18-11-11-47-570_com mixplorer](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/4c33c591-009a-4ef4-9592-acbeaf5bd263)

**Comment by AT0M-03** [comment]
Already did 
Main camera res is 4640×3472(16mp) cam merged 6 frames with this res as in the log i sent
But the final output is 2464×3280(8mp) 
My theory it's because of  jpeg quality?
Maybe i need 100% or 97% to use 16mp because your mod uses 95 by default and there's no option to change it

**Comment by Arnova8G2** [comment]
jpeg quality is only a compression mode.
between 95% and 100% there will be that removal of metadata of a jpeg, below 95% is overpressure of jpeg quality for a maximum compression. resolution is not in this compression mode.

can you share the txt file of the folder gcam/log/XXXX_.... like on the screenshot.
it will help me to understand where the resolution changes

**Comment by AT0M-03** [comment]
![XXXX_20230224_090553_699.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11511826/XXXX_20230224_090553_699.zip)

**Comment by Arnova8G2** [comment]
> ![XXXX_20230224_090553_699.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11511826/XXXX_20230224_090553_699.zip)

Ok, I understood your bug, detection AUX is bad. I will fix it, if not you can do it manually
In custom aux mod - edit id 2 like this

![Screenshot_2023-05-19-04-23-38-656_com google android GoogleCamera-edit](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/b2632552-8c57-4415-b65a-4835729fe9dd)

**Comment by AT0M-03** [comment]
I tried all of them nothing fixed my issue
Just to confirm my problem is in the main sensor gw3 64mp

**Comment by Arnova8G2** [comment]
> I tried all of them nothing fixed my issue Just to confirm my problem is in the main sensor gw3 64mp

test this, clean app cache after install
https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.2

**Comment by AT0M-03** [comment]
Still doesn't fix my issue ![Screenshot_2023-06-03-16-37-14-342_com.google.android.apps.docs.editors.docs.jpg](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/130800451/089516cb-cdbb-471a-84c7-22715973699a)

Gcam merges frames with proper res but it gets lower in the end as in the ss I've sent

**Comment by Arnova8G2** [comment]
@AT0M-03 What is GID used on your device ?

![Screenshot_20230603-180445_Appareil photo](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/0e300ef3-9bdf-4101-9228-7c5b2661ae4c)

**Comment by Arnova8G2** [comment]
@AT0M-03 test this enabled in dev : camera.pixel.disable_crop
https://e.pcloud.link/publink/show?code=XZhhPuZ7RlMbmHSlI0wQSPYzG7WNFLAiF1y

**Comment by AT0M-03** [comment]
![Screenshot_2023-06-03-23-24-20-320_cn.wps.moffice_eng.jpg](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/130800451/30dc0c22-8465-4abb-afae-773fc8b3f019)

Everything seems fine for me I don't have the same problem as hkr mentioned in his 50mp to 8mp issue

**Comment by Arnova8G2** [comment]
#60
