### ISSUE TITLE
Camera crash

### ISSUE THREAD

**Issue by Boolio4040** [Arnova8G2/Gcam_8.7.250.44#6]
Camera crashes after hitting shutter button and the image does not get saved, Model: Oneplus Nord2, 12 gb ram variant
---- Device Info ----
 - Brand : OnePlus
 - Model : DN2101
 - Manufacturer : OnePlus
 - Device : OP515BL1
 - Os version : Android 13 - 4.19.191 
---- Gcam Mod Info ----
 - PackageName : com.google.android.GoogleCamera
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2313

**Comment by Arnova8G2** [comment]
make a logcat

**Comment by Arnova8G2** [comment]
New : 8.1 https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.1
