### ISSUE TITLE
low photo resolution

### ISSUE THREAD

**Issue by HKR001** [Arnova8G2/Gcam_8.7.250.44#60]
sensor size 50mp binned down to 12.5mp but the camera takes only 8mp shot
  ---- Device Info ----
 - Brand : Redmi
 - Model : 2201117TG
 - Manufacturer : Xiaomi
 - Device : spes
 - Os version : Android 13 - 4.19.157-perf-g1f3749ac1a2c
---- Gcam Mod Info ----
 - PackageName : arn.android.gcam
 - VersionName : 8.7.250.build-8.3.230603.0103
[Logs_2023-06-03_09-46-56.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11641658/Logs_2023-06-03_09-46-56.zip)

**Comment by Arnova8G2** [comment]
@HKR001 , I understand the bug the debug gcam displays it

![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/2b480da6-5f2b-4c63-ab3c-50a081e7350c)


here bug 
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/47c941df-2314-4c7a-9be9-f954f93af146)

**Comment by Arnova8G2** [comment]
@HKR001 test this enabled in dev : camera.pixel.disable_crop
https://e.pcloud.link/publink/show?code=XZhhPuZ7RlMbmHSlI0wQSPYzG7WNFLAiF1y

**Comment by AT0M-03** [comment]
@HKR001 Did it fix the issue you're having?

**Comment by Arnova8G2** [comment]
@HKR001 It's good I solved bug, I'm preparing a test

**Comment by Arnova8G2** [comment]
enabled in dev : camera.pixel.array_resolution

https://e.pcloud.link/publink/show?code=XZ6MPuZPVbOMub32yJc8aGBAF5oz0raebR7

**Comment by AT0M-03** [comment]
Enabling it solved my problem i would like to thank you for helping me and for your patience
