### ISSUE TITLE
Crash Log - Xiaomi 13 

### ISSUE THREAD

**Issue by vslmc** [Arnova8G2/Gcam_8.7.250.44#64]
Crash in photo mode but not in video. BSG version ist also crashing, BigKaka version does not crash and work as expected.
If I can provide more help please let me know

[logs_v8.7_2023-06-13_22-09-43.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11738927/logs_v8.7_2023-06-13_22-09-43.txt)

*edit 
Night Sight is actually working, capturing and saving photos

**Comment by Arnova8G2** [comment]
@vslmc disable in dev "topshot_fast_moments_hdr"

**Comment by vslmc** [comment]
Disabling this stops the CrashToLauncher , but capturing does not work.

[log.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11739863/log.zip)

**Comment by Arnova8G2** [comment]
@vslmc  , Clean cache after install
test this : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.4-Beta3

**Comment by vslmc** [comment]
Perfect , it's capturing and saving now. 
Thank you for the quick fix, If I can help with testing let me know, my Xiaomi 13 hast root.
I will attach the log of one successful capture 
[log.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11857534/log.zip)

I also found this in SessionOperation.smali (Miui 14, Android 13), maybe helpfull:
> class public interface abstract Landroidx/camera/extensions/impl/vendortag/SessionOperation;
> super Ljava/lang/Object;
> .source "SessionOperation.java"
> 
> .field public static final AUTO:I = 0xff17 #65303
> .field public static final BOKEH:I = 0xff12 #65298
> .field public static final BOKEH_2X:I = 0xff15 #65301
> .field public static final FACE_RETOUCH:I = 0xff19 #65305
> .field public static final FAST:I = 0xff0f #65295
> .field public static final HDR:I = 0xff18 #65304
> .field public static final HQ:I = 0xff0b #65291
> .field public static final NORMAL:I = 0xff0a #65290
> .field public static final SMART_ENGINE:I = 0xff0e #65294
> .field public static final SUPER_NIGHT:I = 0xff0c #65292
> .field public static final VIDEO_HDR:I = 0xff10 #65296
> .field public static final VIDEO_HDR_10:I = 0xff14 #65300
> .field public static final VIDEO_NORMAL:I = 0xff13 #65299
> .field public static final VIDEO_STABILIZATION:I = 0xff0d #65293
> .field public static final VIDEO_SUPERNIGHT:I = 0xff11 #65297

**Comment by Arnova8G2** [comment]
@vslmc What stock camera do you have ? and if you can share it thanks
Me on the latest [Xiaomi Camera](https://www.apkmirror.com/apk/xiaomi-inc/camera-xiaomi/camera-xiaomi-5-0-000780-2-release/) I have this

![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/2b1ded02-3163-4ad4-835e-e18c8cbbee71)
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/1a839f1c-9a11-4ce2-801c-52663843f645)

**Comment by vslmc** [comment]
I can share the default app , but I got these values from
`/vendor/framework/androidx.camera.extensions.impl.jar`

`/smali_androidx.camera.extensions.impl.jar/androidx/camera/extensions/impl/vendortag/SessionOperation.smali`

I will attach this file first , If you still want the stock app let me know

[androidx.camera.extensions.impl.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11857811/androidx.camera.extensions.impl.zip)

**Comment by vslmc** [comment]
Found more in /odm/etc/camera
Sadly magisk cannot mirror this partition for now but apparently there are working on it

```
##
## camera/xiaomi/mivivendorstreamconfig.json
##
// 0x9002, StreamConfigModeAlgoDualSAT
"VendorOpMode": 36866,
// 0x8001, StreamConfigModeSAT
"MialgoOpMode": 32769,

// 0x9000, StreamConfigModeAlgoDual
"VendorOpMode": 36864,
// 0x8002, StreamConfigModeBokeh
"MialgoOpMode": 32770,

// 0x9003, StreamConfigModeAlgoSingleRTB
"VendorOpMode": 36867,
// 0x8002, StreamConfigModeBokeh
"MialgoOpMode": 32770,

// 0x9001, StreamConfigModeQCFALite
"VendorOpMode": 36865,
// 0x8005, StreamConfigModeMiuiZslFront
"MialgoOpMode": 32773,

// 0x800A, StreamConfigModeMiuiSuperNight
"VendorOpMode": 32778,
// 0x800A, StreamConfigModeMiuiSuperNight
"MialgoOpMode": 32778,

// 0x9004, StreamConfigModeAlgoQCFAMFNR
"VendorOpMode": 36868,
// 0x9004, StreamConfigModeAlgoQcfaMfnr
"MialgoOpMode": 36868,

// 0x9007, StreamConfigModeAlgoManualSuperHD
"VendorOpMode": 36871,
// 0x9007, StreamConfigModeAlgoManualSuperHD
"MialgoOpMode": 36871,

// 0x9008, StreamConfigModeAlgoManual
"VendorOpMode": 36872,
// 0x9008, StreamConfigModeAlgoManual
"MialgoOpMode": 36872,

// 0x9005, StreamConfigModeAlgoNormal
"VendorOpMode": 36869,
// 0x8005, StreamConfigModeMiuiZslFront
"MialgoOpMode": 32773,

// 0x9010, StreamConfigModeThirdCamera
"VendorOpMode": 36880,

##
## camera/xiaomi/ecovendorstreamconfig.json
##
// 0x9010, StreamConfigModeThirdCamera
"SessionOpMode": 65290,
"VendorOpMode": 36866,
```


[odm_etc_camera.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11876757/odm_etc_camera.zip)

**Comment by Arnova8G2** [comment]
Great thanks, I have already added previous operation mode, this one seems to be ones I already use

it's available here : https://dumps.tadiphone.dev/dumps/xiaomi/fuxi/-/blob/missi_phone_global-user-13-TKQ1.220905.001-V14.0.7.0.TMCMIXM-release-keys/odm/etc/camera/xiaomi/mivivendorstreamconfig.json

I will share you a test version on my poco has no effect, on your device it will work

**Comment by Arnova8G2** [comment]
Last Xiaomi Camera 4.5.002870.0 https://www.apkmirror.com/apk/xiaomi-inc/camera-xiaomi/camera-xiaomi-4-5-002870-0-release/

![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/8691a724-1443-4b62-a38f-2d52bf199754)

**Comment by vslmc** [comment]
Yes, I noticed these values are more in line with the ones you use from MiuiCamera

Thank you, I'm gladly testing this new version

*edit
Now I see the new list , I will also try some of these new values

**Comment by Arnova8G2** [comment]
> Yes, I noticed these values are more in line with the ones you use from MiuiCamera
> 
> Thank you, I'm gladly testing this new version
> 
> *edit Now I see the new list , I will also try some of these new values

I check values with a logcat and Camera stock

![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/5191aaa9-a704-4bc0-88e7-2368da8e125e)

**Comment by vslmc** [comment]
I didnt know locat will show the session ID

I tried 33011 and 36871 and it crashed 

[arn_Logs_2023-06-27_09-58-46.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11879709/arn_Logs_2023-06-27_09-58-46.zip)

**Comment by Arnova8G2** [comment]
> I didnt know locat will show the session ID

your device only uses ALGOs
Here is the list that I will add

[Operation Mode.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11886552/Operation.Mode.txt)

**Comment by Arnova8G2** [comment]
@vslmc test version 
https://e.pcloud.link/publink/show?code=XZLDBfZ9d6K0b2pXnmrJlVebNi0M4AR3qGk

**Comment by Vict0rC** [comment]
Hello @vslmc , can I ask what exact version of Xiaomi 13 you have? I have a Xiaomi 13 and I have a [problem switching between lenses](https://github.com/Arnova8G2/Gcam_8.7.250.44/issues/66#issuecomment-1611133297). The video also shows incorrect lens values - it should be 0.6x 1x 2.8x. - However, the Xiaomi stock camera shows lens values of 0.6x 1x 2x 3.2x.
My version is Xiaomi 13 (fuxi), MIUI Global 14.0.22.0 TMCEUXM, Android 13 TKQ1.220905.001

**Comment by vslmc** [comment]
@Vict0rC I actually have the same bug (same device also, fuxi on 14.0.23.6.5 dev beta)
I got it working but only briefly , as soon as I force closed the app the changes where gone. 

I think it's a lens detection problem , I noticed that only the logical wide will be found automaticly. Also other gcam's with working aux uses id:7 not id:0 
If you look at the prefs file you only see 4 detected cams: Tele, UW, Logical, Front and Wide is not to be found 
I added it manually and did go to aux settings in app and change all GIDs to 5 or 7 and ID of logical to 2(UW) and it suddendly worked but this will not allways trigger and I only got this 2-3 times working

But I did managed to make a log of this mode:
[aux_log.zip](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11898182/aux_log.zip)


@Arnova8G2 the new test version works great, most but not all session IDs are working. Should I make a list of working ones ?

**Comment by Arnova8G2** [comment]
@vslmc , Errors in AUX

unique ID per cam
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/e8ec9de9-39f9-411f-896e-2969dcc1b5cc)

unique value per button
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/7336b5a9-6655-4b9e-8db9-c8470ac07289)

For name of buttons crashes, numbers are allowed, I can add text
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/87ca1331-0df0-44fa-8988-7b363d7d23a5)

**Comment by vslmc** [comment]
I see , I will try tomorrow to get a working config done and I will post it here. But to be honest I dont care for aux 🤷

The string there must come from the default app as I have a made a clone from your apk (com.android.camera) to test this new build. Maybe they interfere each other. Strings would be nice but not necessary. 



If I'm allowed to be off topic for a moment:
I tried alot of session IDs and made some experiments 
If two images get blended together with two aligning session IDs (not all have the same crop values or distortions) the image is impressively improved. Atm as I figuered it out, if images are captured in burst mode, each odd frame is under exposed and each even frame over exposed
So my questen is what about changing the session id for each second image of both even and odd runs ? Can it change even quick enough to make burst still viable ?
Also side question: how can I change exposure to be closer or not as dramatic, so the AE score will accept all frames and not even OR odd (atm I didnt see a burst using both but maybe I need to do more daylight shooting)

Now some pictures to show the blending result (snapseed default blending) sabre.arn enabled 

Top=Merge , Bottom=Algo Super Night
![Screenshot_2023-06-28-22-14-57-004_ch want imagecompare](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/28356741/02a6b0d4-dff1-4f68-8c3f-3062579a2bb8)

Top=Merge , Bottom=Algo HDR
![Screenshot_2023-06-28-22-15-03-154_ch want imagecompare](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/28356741/0c07238f-9c63-4f62-9707-16d2fe13a83b)

It has a denoise effect on color grain. Nice
![Screenshot_2023-06-28-22-41-52-534_ch want imagecompare](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/28356741/eee91615-b5c8-4e56-9d14-71197a1b1129)

**Comment by Arnova8G2** [comment]
@vslmc 
Add text button name
Fix error in your log
https://e.pcloud.link/publink/show?code=XZAxWfZEJ6sXNrONcHiylR9vaJcjyqasUNk


If you want to check if your frames are successful, look at the size, because gcam must work with all RAW
![Screenshot_2023-06-28-23-30-17-274_com mixplorer-edit](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/e7d83122-a231-4fdd-95cb-61b4b9e18e89)

Very bad frame selection no preview

![Screenshot_2023-06-28-23-38-01-117_com mixplorer](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/bfa3a40b-24dc-45fe-ad33-4f93d612a232)

Very good selection all have preview

![Screenshot_2023-06-28-23-38-12-157_com mixplorer](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/0e2382f3-1619-4fd8-92b6-d49680a3deb4)

**Comment by vslmc** [comment]
![IMG_20230629_005458](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/28356741/79c7815f-9793-4792-89eb-c45714e0d71c)
Thank you for your effort 
And great its Working
Exept logical, but if I add wide manually it will look like in the image above. If I dont add it it will show 1.4 (and actually thats correct as the viewfinder is zoomed in but the images are 1.0x)


Oh maybe I wrote too confusing. The RAWs in burst mode are all valid, have a preview and can be opend in snapseed 
If I look at summary.txt I find this:
```
Base frame candidate (required) filter 'FrameHasValidData' rejected 1 frames (6 remain).
Base frame candidate (required) filter 'FrameHasValidType' rejected 3 frames (3 remain).

Base frame candidates (3 frames): [1, 0, 1, 0, 1, 0, 0]
Base frame scores: [2.5881, nan, 2.55832, nan, 2.51452, nan, nan]

Merge frame count: 3
```
`FrameHasValidData` is rejecting the ultrashort frame
But `FrameHasValidType` rejects all overexposed frames
Not sure if these get first a frame score and than gets dropped or if they have no score because they are dropped. But the Merge count uses only the 3 odd frames
I thought that this is because the exposure is so different, `exp_time_ms` is 2.10425305 and 8
Could you enlighten me
