### ISSUE TITLE
Crash after pressing Time lapse shutter button 

### ISSUE THREAD

**Issue by mdshafiqulislamshamim** [Arnova8G2/Gcam_8.7.250.44#8]
---- Crash log ----

java.lang.NullPointerException: Attempt to read from field 'java.lang.Object jmp.d' on a null object reference in method 'void hew.run()'at hew.run(PG:10)at bya.run(PG:59)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:210)at android.os.Looper.loop(Looper.java:299)at android.app.ActivityThread.main(ActivityThread.java:8309)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
---- Device Info ----
 - Brand : Redmi
 - Model : 220333QAG
 - Manufacturer : Xiaomi
 - Device : fog
 - Os version : Android 12 - 4.19.157-perf-g85e27949fb09
---- Gcam Mod Info ----
 - PackageName : com.google.android.GoogleCamera
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2313

**Comment by Arnova8G2** [comment]
does not synchronize camcorder, strange time lapse does not use profile of device but that of android

**Comment by mdshafiqulislamshamim** [comment]
> does not synchronize camcorder, strange time lapse does not use profile of device but that of android

Sir, i have to work on which class?? Can u sir give me a hind??

**Comment by Arnova8G2** [comment]
According to your log
![image](https://user-images.githubusercontent.com/40323300/227787328-6cc51488-b782-4f09-8522-bff70d6f1966.png)

hga.
![image](https://user-images.githubusercontent.com/40323300/227787452-31d966f5-67d5-46c8-a3de-b01dbb1e8621.png)

not enough info on the log to say more

**Comment by mdshafiqulislamshamim** [comment]
Thank u so much sir

**Comment by mdshafiqulislamshamim** [comment]
![Screenshot_2023-03-27-09-43-31-782_com.google.android.GoogleCamera.jpg](https://user-images.githubusercontent.com/90249842/227836504-18c35028-b2db-4c8a-99d8-542052d78b80.jpg)

Successfully fixed time lapse. The issue was with profile.

**Comment by mdshafiqulislamshamim** [comment]
![Screenshot_2023-03-27-09-54-17-360-edit_bin.mt.plus~2.jpg](https://user-images.githubusercontent.com/90249842/227837620-20139b5a-6fa0-4677-97ec-295e5110ed63.jpg)

 Check joy.smali file

**Comment by mdshafiqulislamshamim** [comment]
![Screenshot_2023-03-27-13-49-59-772_com.google.android.GoogleCameraEng.jpg](https://user-images.githubusercontent.com/90249842/227877095-f00f5a96-8584-4559-99fa-c6a582fc7538.jpg)

![Screenshot_2023-03-27-13-53-29-535_com.google.android.GoogleCameraEng.jpg](https://user-images.githubusercontent.com/90249842/227877094-e592d60a-ffd1-42b2-8c4b-26af27bca7f1.jpg)

![Screenshot_2023-03-27-13-51-29-581-edit_bin.mt.plus.jpg](https://user-images.githubusercontent.com/90249842/227877096-bb527840-ada7-4d9b-980c-60079352236d.jpg)

![Screenshot_2023-03-27-13-51-48-302-edit_bin.mt.plus.jpg](https://user-images.githubusercontent.com/90249842/227877093-edb49ede-454e-40fb-95f7-2bfc658cb082.jpg)

Working so smooth.
